import type { Metadata } from 'next';
import './globals.css';

import TanStackProvider from '@/components/TanStackProvider/TanStackProvider';
// import Header from '@/components/Header/Header';
// import GreetingBlock from '@/components/GreetingBlock/GreetingBlock';
import AuthProvider from '@/components/AuthProvider/AuthProvider';
import GreetingBlock from '@/components/GreetingBlock/GreetingBlock';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
  sidebar,
}: Readonly<{
  children: React.ReactNode;
  sidebar: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <TanStackProvider>
            {/* <Header /> */}

            <div style={{ margin: '0 auto', display: 'flex' }}>
              <aside>{sidebar}</aside>

              <main>
                <GreetingBlock />
                {children}
              </main>
            </div>
          </TanStackProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
